### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by Britajin** [xiehousheng/SemLA#6]
你好！请问为什么要用可见光图像和它们生成的伪红外图像来训练，而不直接用可见光-红外图像数据集（例如MSRS、Roadscene）进行训练呢？

**Comment by xiehousheng** [comment]
我们不直接使用公开的可见光-红外图像数据集进行训练是因为这类数据集的图像数量不足以使得我们的网络具有更好的泛化能力，并且这类数据集虽然大多都经过手工的配准以得到对齐的图像对，但无法完全确保它们的像素能够在每个位置完全对齐。
相比之下，我们使用可见光图像和伪红外图像作为图像对来训练，这使得我们能够严格保证图像对的对齐质量，并且可以得到足够多数量的训练集。

**Comment by Britajin** [comment]
但是伪红外图像毕竟不是真实的红外图像，用它们进行训练会不会导致难以学习到真实红外图像的特征呢？如果用可见光图像和它们生成的伪红外图像以及可见光-红外图像数据集（例如MSRS、Roadscene）作为训练集，共同进行训练是不是就可以兼顾两者呢？

**Comment by xiehousheng** [comment]
这是一个好问题。在SemLA中，我们认为使用伪红外图像作为训练数据可以在训练集中引入足够的模态差异信息，使得网络能够更适应不同模态的图像配准。然而，由于我们并未尝试过纳入真实的可见光-红外配对图像数据集作为训练集，因此无法针对这个问题给您足够准确的答复。
